travis:
  secure:
    BINSTAR_TOKEN: UIB1KgZQkNOFnD7buT0FXSlCreTtz67DN1XOuyAKzROl5v2Mm01Kg70auAdOd+xq6hBV57KP6fcdWmaEpjEd63iKvy7BJYhY6dIv+xUxXMgcC4ahgx9QinY1VKKpetKhf91y9JctEbUXzTLX09yZ4F+LIpivVKW/Th0l3cCwgSPfy8xM2XNTjGQln+cXoULCRmFPDSt8BvnLXUuy2kX+SvrUOCd7w2crjiJkE71Kf+9oaN3665XPPy2dakOHkMZ3NbAv0STacZaE1NlZVA/gt0933OV9mA9A8grcvfKq45a47t8NdluvHxZycRWJMLUBvuBTzept+FwM2iKa1oq+oyoTDQCOQH4M64e7B/zSWTdDbuBJ6a3R2X9v5BcMchssMtzkBdapVuNdPelKJ/VVVZyScxOqUqI/FjL83xF+KBHdBwoMwjrIopum+euoPE54j/c+IZpI6RmK6MC3/nW9r7XuBOg1P7FnI/2MBdV5uq8Zji5WIRiaQV5wfcoHJ2r7tbGEUi6IsFxTVcnxl3nbYGp/KkndSX7HJoUednkFdP4dTNt5yOCu7ulAHKwymCqG5j6D1QedsCD+AJaJO0OWW7b4XJkuZ2ubtzKyTeyit+hkcMhOKn0F4fNSmXnbVTmuGwTusWOy0XfE4KRsDtIVogugX0mQprjfksE5gEfuaQM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
